
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox reviewQueryVbox;
	private global::Gtk.HBox selectReviewHbox;
	private global::Gtk.Label reviewTargetForQueryLabel;
	private global::Gtk.Entry reviewTargetForQueryEntry;
	private global::Gtk.Button reviewTargetForQueryBrowseButton;
	private global::Gtk.HBox id1Hbox;
	private global::Gtk.Label Id1Label;
	private global::Gtk.SpinButton id1Entry;
	private global::Gtk.HBox id2Hbox;
	private global::Gtk.Label id2Label;
	private global::Gtk.SpinButton id2Entry;
	private global::Gtk.HBox selectionHbox;
	private global::Gtk.Label selectionLabel;
	private global::Gtk.VBox selectionVbox;
	private global::Gtk.HBox userMovieHbox;
	private global::Gtk.RadioButton userRadioButton;
	private global::Gtk.RadioButton movieRadiobutton;
	private global::Gtk.HBox allOrSelectedHbox;
	private global::Gtk.RadioButton selectedRadiobutton;
	private global::Gtk.RadioButton allIdsRadiobutton;
	private global::Gtk.HBox resultHbox;
	private global::Gtk.Label resultLabel;
	private global::Gtk.Entry resultTextbox;
	private global::Gtk.Button calculateButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Similarity calculator");
		this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./netflix.png"));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.reviewQueryVbox = new global::Gtk.VBox ();
		this.reviewQueryVbox.Name = "reviewQueryVbox";
		this.reviewQueryVbox.Spacing = 6;
		// Container child reviewQueryVbox.Gtk.Box+BoxChild
		this.selectReviewHbox = new global::Gtk.HBox ();
		this.selectReviewHbox.Name = "selectReviewHbox";
		this.selectReviewHbox.Spacing = 6;
		// Container child selectReviewHbox.Gtk.Box+BoxChild
		this.reviewTargetForQueryLabel = new global::Gtk.Label ();
		this.reviewTargetForQueryLabel.Name = "reviewTargetForQueryLabel";
		this.reviewTargetForQueryLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Target database :");
		this.selectReviewHbox.Add (this.reviewTargetForQueryLabel);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.selectReviewHbox [this.reviewTargetForQueryLabel]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child selectReviewHbox.Gtk.Box+BoxChild
		this.reviewTargetForQueryEntry = new global::Gtk.Entry ();
		this.reviewTargetForQueryEntry.CanFocus = true;
		this.reviewTargetForQueryEntry.Name = "reviewTargetForQueryEntry";
		this.reviewTargetForQueryEntry.IsEditable = true;
		this.reviewTargetForQueryEntry.InvisibleChar = '●';
		this.selectReviewHbox.Add (this.reviewTargetForQueryEntry);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.selectReviewHbox [this.reviewTargetForQueryEntry]));
		w2.Position = 1;
		// Container child selectReviewHbox.Gtk.Box+BoxChild
		this.reviewTargetForQueryBrowseButton = new global::Gtk.Button ();
		this.reviewTargetForQueryBrowseButton.CanFocus = true;
		this.reviewTargetForQueryBrowseButton.Name = "reviewTargetForQueryBrowseButton";
		this.reviewTargetForQueryBrowseButton.UseUnderline = true;
		this.reviewTargetForQueryBrowseButton.Label = global::Mono.Unix.Catalog.GetString ("Browse");
		this.selectReviewHbox.Add (this.reviewTargetForQueryBrowseButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.selectReviewHbox [this.reviewTargetForQueryBrowseButton]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.reviewQueryVbox.Add (this.selectReviewHbox);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.reviewQueryVbox [this.selectReviewHbox]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child reviewQueryVbox.Gtk.Box+BoxChild
		this.id1Hbox = new global::Gtk.HBox ();
		this.id1Hbox.Name = "id1Hbox";
		this.id1Hbox.Spacing = 6;
		// Container child id1Hbox.Gtk.Box+BoxChild
		this.Id1Label = new global::Gtk.Label ();
		this.Id1Label.Name = "Id1Label";
		this.Id1Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Id 1 :");
		this.id1Hbox.Add (this.Id1Label);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.id1Hbox [this.Id1Label]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child id1Hbox.Gtk.Box+BoxChild
		this.id1Entry = new global::Gtk.SpinButton (0, 1000000, 1);
		this.id1Entry.CanFocus = true;
		this.id1Entry.Name = "id1Entry";
		this.id1Entry.Adjustment.PageIncrement = 10;
		this.id1Entry.ClimbRate = 1;
		this.id1Entry.Numeric = true;
		this.id1Hbox.Add (this.id1Entry);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.id1Hbox [this.id1Entry]));
		w6.Position = 1;
		this.reviewQueryVbox.Add (this.id1Hbox);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.reviewQueryVbox [this.id1Hbox]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child reviewQueryVbox.Gtk.Box+BoxChild
		this.id2Hbox = new global::Gtk.HBox ();
		this.id2Hbox.Name = "id2Hbox";
		this.id2Hbox.Spacing = 6;
		// Container child id2Hbox.Gtk.Box+BoxChild
		this.id2Label = new global::Gtk.Label ();
		this.id2Label.Name = "id2Label";
		this.id2Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Id 2 :");
		this.id2Hbox.Add (this.id2Label);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.id2Hbox [this.id2Label]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child id2Hbox.Gtk.Box+BoxChild
		this.id2Entry = new global::Gtk.SpinButton (0, 1000000, 1);
		this.id2Entry.CanFocus = true;
		this.id2Entry.Name = "id2Entry";
		this.id2Entry.Adjustment.PageIncrement = 10;
		this.id2Entry.ClimbRate = 1;
		this.id2Entry.Numeric = true;
		this.id2Hbox.Add (this.id2Entry);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.id2Hbox [this.id2Entry]));
		w9.Position = 1;
		this.reviewQueryVbox.Add (this.id2Hbox);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.reviewQueryVbox [this.id2Hbox]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child reviewQueryVbox.Gtk.Box+BoxChild
		this.selectionHbox = new global::Gtk.HBox ();
		this.selectionHbox.Name = "selectionHbox";
		this.selectionHbox.Spacing = 6;
		// Container child selectionHbox.Gtk.Box+BoxChild
		this.selectionLabel = new global::Gtk.Label ();
		this.selectionLabel.Name = "selectionLabel";
		this.selectionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Calculate for : ");
		this.selectionHbox.Add (this.selectionLabel);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.selectionHbox [this.selectionLabel]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child selectionHbox.Gtk.Box+BoxChild
		this.selectionVbox = new global::Gtk.VBox ();
		this.selectionVbox.Name = "selectionVbox";
		this.selectionVbox.Spacing = 6;
		// Container child selectionVbox.Gtk.Box+BoxChild
		this.userMovieHbox = new global::Gtk.HBox ();
		this.userMovieHbox.Name = "userMovieHbox";
		this.userMovieHbox.Spacing = 6;
		// Container child userMovieHbox.Gtk.Box+BoxChild
		this.userRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Users"));
		this.userRadioButton.CanFocus = true;
		this.userRadioButton.Name = "userRadioButton";
		this.userRadioButton.DrawIndicator = true;
		this.userRadioButton.UseUnderline = true;
		this.userRadioButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.userMovieHbox.Add (this.userRadioButton);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.userMovieHbox [this.userRadioButton]));
		w12.Position = 0;
		// Container child userMovieHbox.Gtk.Box+BoxChild
		this.movieRadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Movies"));
		this.movieRadiobutton.CanFocus = true;
		this.movieRadiobutton.Name = "movieRadiobutton";
		this.movieRadiobutton.DrawIndicator = true;
		this.movieRadiobutton.UseUnderline = true;
		this.movieRadiobutton.Group = this.userRadioButton.Group;
		this.userMovieHbox.Add (this.movieRadiobutton);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.userMovieHbox [this.movieRadiobutton]));
		w13.PackType = ((global::Gtk.PackType)(1));
		w13.Position = 1;
		this.selectionVbox.Add (this.userMovieHbox);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.selectionVbox [this.userMovieHbox]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child selectionVbox.Gtk.Box+BoxChild
		this.allOrSelectedHbox = new global::Gtk.HBox ();
		this.allOrSelectedHbox.Name = "allOrSelectedHbox";
		this.allOrSelectedHbox.Spacing = 6;
		// Container child allOrSelectedHbox.Gtk.Box+BoxChild
		this.selectedRadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Selected"));
		this.selectedRadiobutton.CanFocus = true;
		this.selectedRadiobutton.Name = "selectedRadiobutton";
		this.selectedRadiobutton.DrawIndicator = true;
		this.selectedRadiobutton.UseUnderline = true;
		this.selectedRadiobutton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.allOrSelectedHbox.Add (this.selectedRadiobutton);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.allOrSelectedHbox [this.selectedRadiobutton]));
		w15.Position = 0;
		// Container child allOrSelectedHbox.Gtk.Box+BoxChild
		this.allIdsRadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("All ids"));
		this.allIdsRadiobutton.CanFocus = true;
		this.allIdsRadiobutton.Name = "allIdsRadiobutton";
		this.allIdsRadiobutton.DrawIndicator = true;
		this.allIdsRadiobutton.UseUnderline = true;
		this.allIdsRadiobutton.Group = this.selectedRadiobutton.Group;
		this.allOrSelectedHbox.Add (this.allIdsRadiobutton);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.allOrSelectedHbox [this.allIdsRadiobutton]));
		w16.Position = 1;
		this.selectionVbox.Add (this.allOrSelectedHbox);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.selectionVbox [this.allOrSelectedHbox]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.selectionHbox.Add (this.selectionVbox);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.selectionHbox [this.selectionVbox]));
		w18.Position = 1;
		this.reviewQueryVbox.Add (this.selectionHbox);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.reviewQueryVbox [this.selectionHbox]));
		w19.Position = 3;
		w19.Expand = false;
		w19.Fill = false;
		// Container child reviewQueryVbox.Gtk.Box+BoxChild
		this.resultHbox = new global::Gtk.HBox ();
		this.resultHbox.Name = "resultHbox";
		this.resultHbox.Spacing = 6;
		// Container child resultHbox.Gtk.Box+BoxChild
		this.resultLabel = new global::Gtk.Label ();
		this.resultLabel.Name = "resultLabel";
		this.resultLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Similarity : ");
		this.resultHbox.Add (this.resultLabel);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.resultHbox [this.resultLabel]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child resultHbox.Gtk.Box+BoxChild
		this.resultTextbox = new global::Gtk.Entry ();
		this.resultTextbox.CanFocus = true;
		this.resultTextbox.Name = "resultTextbox";
		this.resultTextbox.IsEditable = true;
		this.resultTextbox.InvisibleChar = '●';
		this.resultHbox.Add (this.resultTextbox);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.resultHbox [this.resultTextbox]));
		w21.Position = 1;
		this.reviewQueryVbox.Add (this.resultHbox);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.reviewQueryVbox [this.resultHbox]));
		w22.Position = 4;
		w22.Expand = false;
		w22.Fill = false;
		// Container child reviewQueryVbox.Gtk.Box+BoxChild
		this.calculateButton = new global::Gtk.Button ();
		this.calculateButton.CanFocus = true;
		this.calculateButton.Name = "calculateButton";
		this.calculateButton.UseUnderline = true;
		this.calculateButton.Label = global::Mono.Unix.Catalog.GetString ("Calculate");
		this.reviewQueryVbox.Add (this.calculateButton);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.reviewQueryVbox [this.calculateButton]));
		w23.Position = 5;
		w23.Expand = false;
		w23.Fill = false;
		this.Add (this.reviewQueryVbox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 636;
		this.DefaultHeight = 238;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.calculateButton.Clicked += new global::System.EventHandler (this.OnCalculateButtonClicked);
	}
}
