
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook tabpanel;
	private global::Gtk.VBox movieMainVbox;
	private global::Gtk.Table movieTable;
	private global::Gtk.FileChooserButton filechooserMovieSource;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Entry movieTargetEntry;
	private global::Gtk.Button movieTargetBrowseButton;
	private global::Gtk.Label movieSourceLabel;
	private global::Gtk.Label movieTargetLabel;
	private global::Gtk.Statusbar movieStatusbar;
	private global::Gtk.ProgressBar movieProgressbar;
	private global::Gtk.HBox movieHbox;
	private global::Gtk.Button movieImportButton;
	private global::Gtk.Button movieCancelButton;
	private global::Gtk.Label movieTabTitle;
	private global::Gtk.VBox reviewMainVbox;
	private global::Gtk.Table reviewTable;
	private global::Gtk.SpinButton chunkSizeEntry;
	private global::Gtk.Label chunkSizeLabel;
	private global::Gtk.FileChooserButton filechooserReviewSource;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Entry reviewTargetEntry;
	private global::Gtk.Button reviewTargetBrowseButton;
	private global::Gtk.Label reviewSourceLabel;
	private global::Gtk.Label reviewTargetLabel;
	private global::Gtk.SpinButton startFileEntry1;
	private global::Gtk.Label startFileLabel;
	private global::Gtk.Statusbar reviewStatusbar;
	private global::Gtk.ProgressBar reviewProgressbar;
	private global::Gtk.HBox movieHbox1;
	private global::Gtk.Button reviewImportButton;
	private global::Gtk.Button reviewCancelButton;
	private global::Gtk.Label reviewTabTitle;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Netflix");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.tabpanel = new global::Gtk.Notebook ();
		this.tabpanel.CanFocus = true;
		this.tabpanel.Name = "tabpanel";
		this.tabpanel.CurrentPage = 1;
		// Container child tabpanel.Gtk.Notebook+NotebookChild
		this.movieMainVbox = new global::Gtk.VBox ();
		this.movieMainVbox.Name = "movieMainVbox";
		this.movieMainVbox.Spacing = 6;
		// Container child movieMainVbox.Gtk.Box+BoxChild
		this.movieTable = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.movieTable.Name = "movieTable";
		this.movieTable.RowSpacing = ((uint)(6));
		this.movieTable.ColumnSpacing = ((uint)(6));
		// Container child movieTable.Gtk.Table+TableChild
		this.filechooserMovieSource = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Sélectionner un fichier"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserMovieSource.Name = "filechooserMovieSource";
		this.movieTable.Add (this.filechooserMovieSource);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.movieTable [this.filechooserMovieSource]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.XPadding = ((uint)(3));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child movieTable.Gtk.Table+TableChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.movieTargetEntry = new global::Gtk.Entry ();
		this.movieTargetEntry.CanFocus = true;
		this.movieTargetEntry.Name = "movieTargetEntry";
		this.movieTargetEntry.IsEditable = true;
		this.movieTargetEntry.InvisibleChar = '●';
		this.hbox1.Add (this.movieTargetEntry);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.movieTargetEntry]));
		w2.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.movieTargetBrowseButton = new global::Gtk.Button ();
		this.movieTargetBrowseButton.CanFocus = true;
		this.movieTargetBrowseButton.Name = "movieTargetBrowseButton";
		this.movieTargetBrowseButton.UseUnderline = true;
		this.movieTargetBrowseButton.Label = global::Mono.Unix.Catalog.GetString ("Browse");
		this.hbox1.Add (this.movieTargetBrowseButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.movieTargetBrowseButton]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.movieTable.Add (this.hbox1);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.movieTable [this.hbox1]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XPadding = ((uint)(3));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child movieTable.Gtk.Table+TableChild
		this.movieSourceLabel = new global::Gtk.Label ();
		this.movieSourceLabel.Name = "movieSourceLabel";
		this.movieSourceLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Source file :");
		this.movieTable.Add (this.movieSourceLabel);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.movieTable [this.movieSourceLabel]));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child movieTable.Gtk.Table+TableChild
		this.movieTargetLabel = new global::Gtk.Label ();
		this.movieTargetLabel.Name = "movieTargetLabel";
		this.movieTargetLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Target database :");
		this.movieTable.Add (this.movieTargetLabel);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.movieTable [this.movieTargetLabel]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		this.movieMainVbox.Add (this.movieTable);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.movieMainVbox [this.movieTable]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child movieMainVbox.Gtk.Box+BoxChild
		this.movieStatusbar = new global::Gtk.Statusbar ();
		this.movieStatusbar.Name = "movieStatusbar";
		this.movieStatusbar.Spacing = 6;
		// Container child movieStatusbar.Gtk.Box+BoxChild
		this.movieProgressbar = new global::Gtk.ProgressBar ();
		this.movieProgressbar.Name = "movieProgressbar";
		this.movieStatusbar.Add (this.movieProgressbar);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.movieStatusbar [this.movieProgressbar]));
		w8.Position = 1;
		this.movieMainVbox.Add (this.movieStatusbar);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.movieMainVbox [this.movieStatusbar]));
		w9.PackType = ((global::Gtk.PackType)(1));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child movieMainVbox.Gtk.Box+BoxChild
		this.movieHbox = new global::Gtk.HBox ();
		this.movieHbox.Name = "movieHbox";
		this.movieHbox.Spacing = 6;
		// Container child movieHbox.Gtk.Box+BoxChild
		this.movieImportButton = new global::Gtk.Button ();
		this.movieImportButton.CanFocus = true;
		this.movieImportButton.Name = "movieImportButton";
		this.movieImportButton.UseUnderline = true;
		this.movieImportButton.Label = global::Mono.Unix.Catalog.GetString ("Import");
		this.movieHbox.Add (this.movieImportButton);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.movieHbox [this.movieImportButton]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		w10.Padding = ((uint)(3));
		// Container child movieHbox.Gtk.Box+BoxChild
		this.movieCancelButton = new global::Gtk.Button ();
		this.movieCancelButton.CanFocus = true;
		this.movieCancelButton.Name = "movieCancelButton";
		this.movieCancelButton.UseUnderline = true;
		this.movieCancelButton.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
		this.movieHbox.Add (this.movieCancelButton);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.movieHbox [this.movieCancelButton]));
		w11.PackType = ((global::Gtk.PackType)(1));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.movieMainVbox.Add (this.movieHbox);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.movieMainVbox [this.movieHbox]));
		w12.PackType = ((global::Gtk.PackType)(1));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.tabpanel.Add (this.movieMainVbox);
		// Notebook tab
		this.movieTabTitle = new global::Gtk.Label ();
		this.movieTabTitle.Name = "movieTabTitle";
		this.movieTabTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Movie");
		this.tabpanel.SetTabLabel (this.movieMainVbox, this.movieTabTitle);
		this.movieTabTitle.ShowAll ();
		// Container child tabpanel.Gtk.Notebook+NotebookChild
		this.reviewMainVbox = new global::Gtk.VBox ();
		this.reviewMainVbox.Name = "reviewMainVbox";
		this.reviewMainVbox.Spacing = 6;
		// Container child reviewMainVbox.Gtk.Box+BoxChild
		this.reviewTable = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
		this.reviewTable.Name = "reviewTable";
		this.reviewTable.RowSpacing = ((uint)(6));
		this.reviewTable.ColumnSpacing = ((uint)(6));
		// Container child reviewTable.Gtk.Table+TableChild
		this.chunkSizeEntry = new global::Gtk.SpinButton (0, 10000, 1);
		this.chunkSizeEntry.CanFocus = true;
		this.chunkSizeEntry.Name = "chunkSizeEntry";
		this.chunkSizeEntry.Adjustment.PageIncrement = 10;
		this.chunkSizeEntry.ClimbRate = 10;
		this.chunkSizeEntry.Numeric = true;
		this.chunkSizeEntry.Value = 200;
		this.reviewTable.Add (this.chunkSizeEntry);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.chunkSizeEntry]));
		w14.TopAttach = ((uint)(2));
		w14.BottomAttach = ((uint)(3));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.XPadding = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.chunkSizeLabel = new global::Gtk.Label ();
		this.chunkSizeLabel.TooltipMarkup = "Number of file to import together";
		this.chunkSizeLabel.Name = "chunkSizeLabel";
		this.chunkSizeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Chunk size :");
		this.reviewTable.Add (this.chunkSizeLabel);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.chunkSizeLabel]));
		w15.TopAttach = ((uint)(2));
		w15.BottomAttach = ((uint)(3));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.filechooserReviewSource = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Sélectionner un dossier"), ((global::Gtk.FileChooserAction)(2)));
		this.filechooserReviewSource.Name = "filechooserReviewSource";
		this.reviewTable.Add (this.filechooserReviewSource);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.filechooserReviewSource]));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XPadding = ((uint)(3));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.reviewTargetEntry = new global::Gtk.Entry ();
		this.reviewTargetEntry.CanFocus = true;
		this.reviewTargetEntry.Name = "reviewTargetEntry";
		this.reviewTargetEntry.IsEditable = true;
		this.reviewTargetEntry.InvisibleChar = '●';
		this.hbox2.Add (this.reviewTargetEntry);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.reviewTargetEntry]));
		w17.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.reviewTargetBrowseButton = new global::Gtk.Button ();
		this.reviewTargetBrowseButton.CanFocus = true;
		this.reviewTargetBrowseButton.Name = "reviewTargetBrowseButton";
		this.reviewTargetBrowseButton.UseUnderline = true;
		this.reviewTargetBrowseButton.Label = global::Mono.Unix.Catalog.GetString ("Browse");
		this.hbox2.Add (this.reviewTargetBrowseButton);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.reviewTargetBrowseButton]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.reviewTable.Add (this.hbox2);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.hbox2]));
		w19.TopAttach = ((uint)(1));
		w19.BottomAttach = ((uint)(2));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XPadding = ((uint)(3));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.reviewSourceLabel = new global::Gtk.Label ();
		this.reviewSourceLabel.Name = "reviewSourceLabel";
		this.reviewSourceLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Source folder :");
		this.reviewTable.Add (this.reviewSourceLabel);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.reviewSourceLabel]));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.reviewTargetLabel = new global::Gtk.Label ();
		this.reviewTargetLabel.Name = "reviewTargetLabel";
		this.reviewTargetLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Target database :");
		this.reviewTable.Add (this.reviewTargetLabel);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.reviewTargetLabel]));
		w21.TopAttach = ((uint)(1));
		w21.BottomAttach = ((uint)(2));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.startFileEntry1 = new global::Gtk.SpinButton (0, 20000, 1);
		this.startFileEntry1.CanFocus = true;
		this.startFileEntry1.Name = "startFileEntry1";
		this.startFileEntry1.Adjustment.PageIncrement = 10;
		this.startFileEntry1.ClimbRate = 1;
		this.startFileEntry1.Numeric = true;
		this.reviewTable.Add (this.startFileEntry1);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.startFileEntry1]));
		w22.TopAttach = ((uint)(3));
		w22.BottomAttach = ((uint)(4));
		w22.LeftAttach = ((uint)(1));
		w22.RightAttach = ((uint)(2));
		w22.XPadding = ((uint)(3));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.startFileLabel = new global::Gtk.Label ();
		this.startFileLabel.TooltipMarkup = "The movie id of the file you want to start with (import in several times)";
		this.startFileLabel.Name = "startFileLabel";
		this.startFileLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Start file :");
		this.reviewTable.Add (this.startFileLabel);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.startFileLabel]));
		w23.TopAttach = ((uint)(3));
		w23.BottomAttach = ((uint)(4));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		this.reviewMainVbox.Add (this.reviewTable);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.reviewMainVbox [this.reviewTable]));
		w24.Position = 0;
		w24.Padding = ((uint)(5));
		// Container child reviewMainVbox.Gtk.Box+BoxChild
		this.reviewStatusbar = new global::Gtk.Statusbar ();
		this.reviewStatusbar.Name = "reviewStatusbar";
		this.reviewStatusbar.Spacing = 6;
		// Container child reviewStatusbar.Gtk.Box+BoxChild
		this.reviewProgressbar = new global::Gtk.ProgressBar ();
		this.reviewProgressbar.Name = "reviewProgressbar";
		this.reviewStatusbar.Add (this.reviewProgressbar);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.reviewStatusbar [this.reviewProgressbar]));
		w25.Position = 1;
		this.reviewMainVbox.Add (this.reviewStatusbar);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.reviewMainVbox [this.reviewStatusbar]));
		w26.PackType = ((global::Gtk.PackType)(1));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		// Container child reviewMainVbox.Gtk.Box+BoxChild
		this.movieHbox1 = new global::Gtk.HBox ();
		this.movieHbox1.Name = "movieHbox1";
		this.movieHbox1.Spacing = 6;
		// Container child movieHbox1.Gtk.Box+BoxChild
		this.reviewImportButton = new global::Gtk.Button ();
		this.reviewImportButton.CanFocus = true;
		this.reviewImportButton.Name = "reviewImportButton";
		this.reviewImportButton.UseUnderline = true;
		this.reviewImportButton.Label = global::Mono.Unix.Catalog.GetString ("Import");
		this.movieHbox1.Add (this.reviewImportButton);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.movieHbox1 [this.reviewImportButton]));
		w27.PackType = ((global::Gtk.PackType)(1));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		w27.Padding = ((uint)(3));
		// Container child movieHbox1.Gtk.Box+BoxChild
		this.reviewCancelButton = new global::Gtk.Button ();
		this.reviewCancelButton.CanFocus = true;
		this.reviewCancelButton.Name = "reviewCancelButton";
		this.reviewCancelButton.UseUnderline = true;
		this.reviewCancelButton.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
		this.movieHbox1.Add (this.reviewCancelButton);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.movieHbox1 [this.reviewCancelButton]));
		w28.PackType = ((global::Gtk.PackType)(1));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.reviewMainVbox.Add (this.movieHbox1);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.reviewMainVbox [this.movieHbox1]));
		w29.PackType = ((global::Gtk.PackType)(1));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.tabpanel.Add (this.reviewMainVbox);
		global::Gtk.Notebook.NotebookChild w30 = ((global::Gtk.Notebook.NotebookChild)(this.tabpanel [this.reviewMainVbox]));
		w30.Position = 1;
		// Notebook tab
		this.reviewTabTitle = new global::Gtk.Label ();
		this.reviewTabTitle.Name = "reviewTabTitle";
		this.reviewTabTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Review");
		this.tabpanel.SetTabLabel (this.reviewMainVbox, this.reviewTabTitle);
		this.reviewTabTitle.ShowAll ();
		this.Add (this.tabpanel);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 501;
		this.DefaultHeight = 258;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.movieTargetBrowseButton.Clicked += new global::System.EventHandler (this.OnMovieTargetBrowseButtonClicked);
		this.movieCancelButton.Clicked += new global::System.EventHandler (this.OnMovieCancelButtonClicked);
		this.movieImportButton.Clicked += new global::System.EventHandler (this.OnMovieImportButtonClicked);
		this.reviewTargetBrowseButton.Clicked += new global::System.EventHandler (this.OnReviewTargetBrowseButtonClicked);
		this.reviewCancelButton.Clicked += new global::System.EventHandler (this.OnReviewCancelButtonClicked);
		this.reviewImportButton.Clicked += new global::System.EventHandler (this.OnReviewImportButtonClicked);
	}
}
