
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook tabpanel;
	private global::Gtk.VBox movieMainVbox;
	private global::Gtk.Table movieTable;
	private global::Gtk.FileChooserButton filechooserMovieSource;
	private global::Gtk.FileChooserButton filechooserReviewTarget;
	private global::Gtk.Label movieSourceLabel;
	private global::Gtk.Label movieTargetLabel;
	private global::Gtk.Statusbar movieStatusbar;
	private global::Gtk.ProgressBar reviewProgressbar1;
	private global::Gtk.HBox movieHbox;
	private global::Gtk.Button movieImportButton;
	private global::Gtk.Button movieCancelButton;
	private global::Gtk.Label movieTabTitle;
	private global::Gtk.VBox reviewMainVbox;
	private global::Gtk.Table reviewTable;
	private global::Gtk.SpinButton chunkSizeEntry;
	private global::Gtk.Label chunkSizeLabel;
	private global::Gtk.FileChooserButton filechooserMovieTarget;
	private global::Gtk.FileChooserButton filechooserReviewSource;
	private global::Gtk.Label reviewSourceLabel;
	private global::Gtk.Label reviewTargetLabel;
	private global::Gtk.SpinButton startFileEntry1;
	private global::Gtk.Label startFileLabel;
	private global::Gtk.Statusbar reviewStatusbar;
	private global::Gtk.ProgressBar reviewProgressbar;
	private global::Gtk.HBox movieHbox1;
	private global::Gtk.Button reviewImportButton;
	private global::Gtk.Button reviewCancelButton;
	private global::Gtk.Label reviewTabTitle;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Netflix");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.tabpanel = new global::Gtk.Notebook ();
		this.tabpanel.CanFocus = true;
		this.tabpanel.Name = "tabpanel";
		this.tabpanel.CurrentPage = 0;
		// Container child tabpanel.Gtk.Notebook+NotebookChild
		this.movieMainVbox = new global::Gtk.VBox ();
		this.movieMainVbox.Name = "movieMainVbox";
		this.movieMainVbox.Spacing = 6;
		// Container child movieMainVbox.Gtk.Box+BoxChild
		this.movieTable = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.movieTable.Name = "movieTable";
		this.movieTable.RowSpacing = ((uint)(6));
		this.movieTable.ColumnSpacing = ((uint)(6));
		// Container child movieTable.Gtk.Table+TableChild
		this.filechooserMovieSource = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Sélectionner un fichier"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserMovieSource.Name = "filechooserMovieSource";
		this.movieTable.Add (this.filechooserMovieSource);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.movieTable [this.filechooserMovieSource]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child movieTable.Gtk.Table+TableChild
		this.filechooserReviewTarget = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Sélectionner un fichier"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserReviewTarget.Name = "filechooserReviewTarget";
		this.movieTable.Add (this.filechooserReviewTarget);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.movieTable [this.filechooserReviewTarget]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child movieTable.Gtk.Table+TableChild
		this.movieSourceLabel = new global::Gtk.Label ();
		this.movieSourceLabel.Name = "movieSourceLabel";
		this.movieSourceLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Source file :");
		this.movieTable.Add (this.movieSourceLabel);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.movieTable [this.movieSourceLabel]));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child movieTable.Gtk.Table+TableChild
		this.movieTargetLabel = new global::Gtk.Label ();
		this.movieTargetLabel.Name = "movieTargetLabel";
		this.movieTargetLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Target database :");
		this.movieTable.Add (this.movieTargetLabel);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.movieTable [this.movieTargetLabel]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		this.movieMainVbox.Add (this.movieTable);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.movieMainVbox [this.movieTable]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child movieMainVbox.Gtk.Box+BoxChild
		this.movieStatusbar = new global::Gtk.Statusbar ();
		this.movieStatusbar.Name = "movieStatusbar";
		this.movieStatusbar.Spacing = 6;
		// Container child movieStatusbar.Gtk.Box+BoxChild
		this.reviewProgressbar1 = new global::Gtk.ProgressBar ();
		this.reviewProgressbar1.Name = "reviewProgressbar1";
		this.movieStatusbar.Add (this.reviewProgressbar1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.movieStatusbar [this.reviewProgressbar1]));
		w6.Position = 1;
		this.movieMainVbox.Add (this.movieStatusbar);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.movieMainVbox [this.movieStatusbar]));
		w7.PackType = ((global::Gtk.PackType)(1));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child movieMainVbox.Gtk.Box+BoxChild
		this.movieHbox = new global::Gtk.HBox ();
		this.movieHbox.Name = "movieHbox";
		this.movieHbox.Spacing = 6;
		// Container child movieHbox.Gtk.Box+BoxChild
		this.movieImportButton = new global::Gtk.Button ();
		this.movieImportButton.CanFocus = true;
		this.movieImportButton.Name = "movieImportButton";
		this.movieImportButton.UseUnderline = true;
		this.movieImportButton.Label = global::Mono.Unix.Catalog.GetString ("Import");
		this.movieHbox.Add (this.movieImportButton);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.movieHbox [this.movieImportButton]));
		w8.PackType = ((global::Gtk.PackType)(1));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child movieHbox.Gtk.Box+BoxChild
		this.movieCancelButton = new global::Gtk.Button ();
		this.movieCancelButton.CanFocus = true;
		this.movieCancelButton.Name = "movieCancelButton";
		this.movieCancelButton.UseUnderline = true;
		this.movieCancelButton.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
		this.movieHbox.Add (this.movieCancelButton);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.movieHbox [this.movieCancelButton]));
		w9.PackType = ((global::Gtk.PackType)(1));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.movieMainVbox.Add (this.movieHbox);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.movieMainVbox [this.movieHbox]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.tabpanel.Add (this.movieMainVbox);
		// Notebook tab
		this.movieTabTitle = new global::Gtk.Label ();
		this.movieTabTitle.Name = "movieTabTitle";
		this.movieTabTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Movie");
		this.tabpanel.SetTabLabel (this.movieMainVbox, this.movieTabTitle);
		this.movieTabTitle.ShowAll ();
		// Container child tabpanel.Gtk.Notebook+NotebookChild
		this.reviewMainVbox = new global::Gtk.VBox ();
		this.reviewMainVbox.Name = "reviewMainVbox";
		this.reviewMainVbox.Spacing = 6;
		// Container child reviewMainVbox.Gtk.Box+BoxChild
		this.reviewTable = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
		this.reviewTable.Name = "reviewTable";
		this.reviewTable.RowSpacing = ((uint)(6));
		this.reviewTable.ColumnSpacing = ((uint)(6));
		// Container child reviewTable.Gtk.Table+TableChild
		this.chunkSizeEntry = new global::Gtk.SpinButton (0, 10000, 1);
		this.chunkSizeEntry.CanFocus = true;
		this.chunkSizeEntry.Name = "chunkSizeEntry";
		this.chunkSizeEntry.Adjustment.PageIncrement = 10;
		this.chunkSizeEntry.ClimbRate = 10;
		this.chunkSizeEntry.Numeric = true;
		this.chunkSizeEntry.Value = 200;
		this.reviewTable.Add (this.chunkSizeEntry);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.chunkSizeEntry]));
		w12.TopAttach = ((uint)(2));
		w12.BottomAttach = ((uint)(3));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.XPadding = ((uint)(3));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.chunkSizeLabel = new global::Gtk.Label ();
		this.chunkSizeLabel.TooltipMarkup = "Number of file to import together";
		this.chunkSizeLabel.Name = "chunkSizeLabel";
		this.chunkSizeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Chunk size :");
		this.reviewTable.Add (this.chunkSizeLabel);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.chunkSizeLabel]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.filechooserMovieTarget = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Sélectionner un fichier"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserMovieTarget.Name = "filechooserMovieTarget";
		this.reviewTable.Add (this.filechooserMovieTarget);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.filechooserMovieTarget]));
		w14.TopAttach = ((uint)(1));
		w14.BottomAttach = ((uint)(2));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.XPadding = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.filechooserReviewSource = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Sélectionner un dossier"), ((global::Gtk.FileChooserAction)(2)));
		this.filechooserReviewSource.Name = "filechooserReviewSource";
		this.reviewTable.Add (this.filechooserReviewSource);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.filechooserReviewSource]));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.XPadding = ((uint)(3));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.reviewSourceLabel = new global::Gtk.Label ();
		this.reviewSourceLabel.Name = "reviewSourceLabel";
		this.reviewSourceLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Source folder :");
		this.reviewTable.Add (this.reviewSourceLabel);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.reviewSourceLabel]));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.reviewTargetLabel = new global::Gtk.Label ();
		this.reviewTargetLabel.Name = "reviewTargetLabel";
		this.reviewTargetLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Target database :");
		this.reviewTable.Add (this.reviewTargetLabel);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.reviewTargetLabel]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.startFileEntry1 = new global::Gtk.SpinButton (0, 20000, 1);
		this.startFileEntry1.CanFocus = true;
		this.startFileEntry1.Name = "startFileEntry1";
		this.startFileEntry1.Adjustment.PageIncrement = 10;
		this.startFileEntry1.ClimbRate = 1;
		this.startFileEntry1.Numeric = true;
		this.reviewTable.Add (this.startFileEntry1);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.startFileEntry1]));
		w18.TopAttach = ((uint)(3));
		w18.BottomAttach = ((uint)(4));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XPadding = ((uint)(3));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child reviewTable.Gtk.Table+TableChild
		this.startFileLabel = new global::Gtk.Label ();
		this.startFileLabel.TooltipMarkup = "The movie id of the file you want to start with (import in several times)";
		this.startFileLabel.Name = "startFileLabel";
		this.startFileLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Start file :");
		this.reviewTable.Add (this.startFileLabel);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.reviewTable [this.startFileLabel]));
		w19.TopAttach = ((uint)(3));
		w19.BottomAttach = ((uint)(4));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		this.reviewMainVbox.Add (this.reviewTable);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.reviewMainVbox [this.reviewTable]));
		w20.Position = 0;
		w20.Padding = ((uint)(5));
		// Container child reviewMainVbox.Gtk.Box+BoxChild
		this.reviewStatusbar = new global::Gtk.Statusbar ();
		this.reviewStatusbar.Name = "reviewStatusbar";
		this.reviewStatusbar.Spacing = 6;
		// Container child reviewStatusbar.Gtk.Box+BoxChild
		this.reviewProgressbar = new global::Gtk.ProgressBar ();
		this.reviewProgressbar.Name = "reviewProgressbar";
		this.reviewStatusbar.Add (this.reviewProgressbar);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.reviewStatusbar [this.reviewProgressbar]));
		w21.Position = 1;
		this.reviewMainVbox.Add (this.reviewStatusbar);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.reviewMainVbox [this.reviewStatusbar]));
		w22.PackType = ((global::Gtk.PackType)(1));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child reviewMainVbox.Gtk.Box+BoxChild
		this.movieHbox1 = new global::Gtk.HBox ();
		this.movieHbox1.Name = "movieHbox1";
		this.movieHbox1.Spacing = 6;
		// Container child movieHbox1.Gtk.Box+BoxChild
		this.reviewImportButton = new global::Gtk.Button ();
		this.reviewImportButton.CanFocus = true;
		this.reviewImportButton.Name = "reviewImportButton";
		this.reviewImportButton.UseUnderline = true;
		this.reviewImportButton.Label = global::Mono.Unix.Catalog.GetString ("Import");
		this.movieHbox1.Add (this.reviewImportButton);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.movieHbox1 [this.reviewImportButton]));
		w23.PackType = ((global::Gtk.PackType)(1));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		w23.Padding = ((uint)(3));
		// Container child movieHbox1.Gtk.Box+BoxChild
		this.reviewCancelButton = new global::Gtk.Button ();
		this.reviewCancelButton.CanFocus = true;
		this.reviewCancelButton.Name = "reviewCancelButton";
		this.reviewCancelButton.UseUnderline = true;
		this.reviewCancelButton.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
		this.movieHbox1.Add (this.reviewCancelButton);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.movieHbox1 [this.reviewCancelButton]));
		w24.PackType = ((global::Gtk.PackType)(1));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		this.reviewMainVbox.Add (this.movieHbox1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.reviewMainVbox [this.movieHbox1]));
		w25.PackType = ((global::Gtk.PackType)(1));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		this.tabpanel.Add (this.reviewMainVbox);
		global::Gtk.Notebook.NotebookChild w26 = ((global::Gtk.Notebook.NotebookChild)(this.tabpanel [this.reviewMainVbox]));
		w26.Position = 1;
		// Notebook tab
		this.reviewTabTitle = new global::Gtk.Label ();
		this.reviewTabTitle.Name = "reviewTabTitle";
		this.reviewTabTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Review");
		this.tabpanel.SetTabLabel (this.reviewMainVbox, this.reviewTabTitle);
		this.reviewTabTitle.ShowAll ();
		this.Add (this.tabpanel);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 501;
		this.DefaultHeight = 258;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
